routes/admin.php
<?php

use App\Http\Controllers\Admin\{
    AdminAuthenticatedSessionController,
    AdminController,
    BrandController,
    CategoryController,
    CountryController,
    CouponController,
    DashboardController,
    HomeProductCategoryController,
    OrderController,
    PasswordController,
    PermissionController,
    PostCategoryController,
    PostController,
    ProductController,
    ProductImageController,
    ProductStockController,
    ProfileInformationController,
    ReportController,
    ReviewController,
    RoleController,
    SeoSettingController,
    SiteSettingController,
    SliderController,
    UserController,
};
use Illuminate\Support\Facades\Route;


Route::prefix('admin')->group(function () {
    Route::middleware('guest:admin')->group(function () {
        Route::view('/', 'pages.admin.login');
        Route::view('/login', 'pages.admin.login');
        Route::post('/login', [AdminAuthenticatedSessionController::class, 'store'])->name('login');
    });

    Route::group([
        'middleware' => ['auth:sanctum,admin', 'verified', 'auth:admin'],
    ], function () {
        Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

        Route::view('/profile', 'profile.admin.show')->name('profile.show');
        Route::put('/profile-information', [ProfileInformationController::class, 'update'])->name('profile-information.update');
        Route::put('/password', [PasswordController::class, 'update'])->name('password.update');

        Route::resource('brands', BrandController::class)->except(['create', 'show']);
        Route::resource('categories', CategoryController::class)->except(['create', 'show']);

        Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
            Route::get('/toggle-status/{product}', [ProductController::class, 'toggleStatus'])->name('toggle-status');
            Route::get('/images/{image}/delete', [ProductImageController::class, 'deleteProductImage'])->name('image.delete');
            Route::resource('images', ProductImageController::class)->only(['store'])->names(['store' => 'images.update']);
            Route::resource('stock', ProductStockController::class)->only(['index'])->names(['index' => 'stock.list']);
            Route::post('/import-data',[ProductController::class,'importData'])->name('import-data');
            Route::get('delete-all',function(){
                DB::table('products')->delete();
            return back()->with('success','table cleared.');
            })->name('delete-all');
        });
        Route::resource('products', ProductController::class)->except(['show']);

        Route::get('/coupons/toggle-status/{coupon}', [CouponController::class, 'toggleStatus'])->name('coupons.toggle-status');
        Route::resource('coupons', CouponController::class)->except(['show', 'create']);
        Route::resource('countries', CountryController::class)->except(['create', 'show']);
        
        Route::get('/sliders/toggle-status/{slider}', [SliderController::class, 'toggleStatus'])->name('sliders.toggle-status');
        Route::resource('sliders', SliderController::class)->except(['create', 'show']);

        Route::resource('home-category',HomeProductCategoryController::class)->only(['update','index'])->names([
            'index' => 'product.category.tabs',
            'update' => 'product.category.update',
        ]);

        Route::get('/orders/updateStatus/{order}', [OrderController::class, 'updateStatus'])->name('orders.updateStatus');
        Route::get('/return-orders/{order}/approve', [OrderController::class, 'returnApprove'])->name('return.order.approve');
        Route::get('/invoice/{order}/download', [OrderController::class, 'invoiceDownload'])->name('order.invoice.download');
        Route::resource('orders',OrderController::class)->only(['index','show']);


        Route::get('/reports', [ReportController::class, 'index'])->name('reports.index');

        Route::resource('users', UserController::class)->only(['index']);

        Route::group(['prefix' => 'blog', 'as' => 'blog.'], function () {
            Route::resource('postCategories', PostCategoryController::class)->except(['show', 'create']);
            Route::resource('posts', PostController::class)->except(['show']);
        });

        Route::group(['as' => 'settings.'], function () {
            Route::resource('siteSetting', SiteSettingController::class)->only(['edit', 'update']);
            Route::resource('seoSetting', SeoSettingController::class)->only(['edit', 'update']);
        });

        Route::get('/reviews/{review}/approve', [ReviewController::class, 'approve'])->name('reviews.approve');
        Route::resource('reviews', ReviewController::class)->only('index', 'destroy');

        Route::resource('roles', RoleController::class)->except(['create', 'show']);
        Route::resource('permissions', PermissionController::class)->except(['create', 'show']);

        Route::resource('admins', AdminController::class);

        Route::view('/menu', 'pages.admin.menu')->name('menu');

        Route::post('/logout', [AdminAuthenticatedSessionController::class, 'destroy'])->name('logout');
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\{
    EmailVerificationController,
    FrontendController,
};
use App\Http\Controllers\Frontend\ProductDetailController;
use App\Http\Controllers\User\{
    OrderController,
    ReviewController,
    ProfileInformationController,
    CheckoutController,
    CartController,
    CartCouponController,
    PasswordController,
    UserController,
    WishlistController,
};
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']
], function () {
    Route::get('/', [FrontendController::class, 'home'])->name('home');
    Route::get('/details/{slug}', [ProductDetailController::class, 'show'])->name('product.details');
    Route::get('/product/tag/{tag}', [FrontendController::class, 'fetchProductByTag'])->name('product.tag');
    Route::get('/category/{slug}', [FrontendController::class, 'fetchProductByCategory'])->name('product.category');
    Route::get('/product/modal/{product}', [FrontendController::class, 'addToCartModal'])->name('product.modal');

    Route::get('/shop', [FrontendController::class, 'viewShop'])->name('shop');

    Route::group(['prefix' => 'carts', 'as' => 'carts.'], function () {
        Route::resource('coupon', CartCouponController::class)->only(['store', 'destroy']);
        Route::get('/mini-cart', [CartController::class, 'getMiniCart'])->name('mini.cart');
    });
    Route::resource('carts', CartController::class)->except(['create', 'edit'])->names(['show' => 'carts.details']);

    Route::get('/products/search', [FrontendController::class, 'productSearch'])->name('products.search');
    Route::post('/products/search-dropdown', [FrontendController::class, 'productSearchDropdown'])->name('products.search-dropdown');

    Route::group(['prefix' => 'blog', 'as' => 'blog.'], function () {
        Route::get('/', [FrontendController::class, 'blogList'])->name('index');
        Route::get('/{slug}/{id}/details', [FrontendController::class, 'blogDetails'])->name('details');
        Route::get('/{post_category}/category', [FrontendController::class, 'blogPostCategory'])->name('post.category');
    });

    Route::resource('wishlist', WishlistController::class)->only(['index', 'store', 'destroy']);

    Route::group(['middleware' => ['auth', 'user']], function () {
        Route::group(['middleware' => ['verified'], 'prefix' => 'user', 'as' => 'user.'], function () {
            Route::view('/', 'dashboard');
            Route::view('/dashboard', 'dashboard')->name('dashboard');

            Route::view('/profile', 'profile.show')->name('profile.show');
            Route::put('/profile-information', [ProfileInformationController::class, 'update'])->name('profile.update');
            Route::put('/password', [PasswordController::class, 'update'])->name('password.update');

            Route::post('reviews', [ReviewController::class, 'store'])->name('reviews.store');

            Route::resource('checkout', CheckoutController::class)->only(['index', 'store'])->names(['index' => 'checkout.view']);

            Route::group(['prefix' => 'orders'], function () {
                Route::get('/invoice/{order}/download', [OrderController::class, 'download'])->name('order.invoice.download');
                Route::get('/tracking', [OrderController::class, 'tracking'])->name('order.tracking');
                Route::post('/{order}/return', [OrderController::class, 'returnOrderRequest'])->name('order.return');
            });
            Route::resource('orders', OrderController::class)->only(['index', 'show']);
        });

        Route::group(['prefix' => 'email'], function () {
            Route::get('/verify/{id}/{hash}', [EmailVerificationController::class, 'handler'])->middleware(['signed'])->name('verification.verify');
            Route::view('/verify', 'auth.verify-email')->name('verification.notice');
            Route::post('/verification-notification', [EmailVerificationController::class, 'resend'])->middleware(['throttle:6,1'])->name('verification.send');
        });

        Route::post('/logout', [UserController::class, 'logout'])->name('logout');
    });
});

app/Http/Controllers/Admin/ReportController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;

class ReportController extends Controller
{
    public function index()
    {
        return view('pages.admin.report.index');
    }
}

resources/views/pages/admin/report/index.blade.php
@extends('layouts.admin.master')
@section('title', 'All Report')
@section('content')
    <div class="content-wrapper">
        <div class="container-full">
            <div class="content-header">
                <div class="d-flex align-items-center">
                    <div class="mr-auto">
                        <div class="d-inline-block align-items-center">
                            <nav>
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{ route('admin.reports.index') }}"><i
                                                class="mdi mdi-home-outline"></i></a></li>
                                    <li class="breadcrumb-item" aria-current="page">
                                        Admin
                                    </li>
                                    <li class="breadcrumb-item active" aria-current="page">All Report</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <section class="content">
                <div class="row">
                    <!--   ------------ Add Search Page -------- -->
                    <div class="col-4">
                        <div class="box">
                            <div class="box-header with-border">
                                <h3 class="box-title">Search By Date </h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <div class="table-responsive">
                                    <div class="form-group">
                                        <h5>Select Date <span class="text-danger">*</span></h5>
                                        <div class="controls">
                                            <input type="date" name="date" id='date' class="form-control">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /.box-body -->
                        </div>
                        <!-- /.box -->
                    </div>
                    <div class="col-4">
                        <div class="box">
                            <div class="box-header with-border">
                                <h3 class="box-title">Search By Month </h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <div class="table-responsive">
                                    <div class="form-group">
                                        <h5>Select Month <span class="text-danger">*</span></h5>
                                        <div class="controls">
                                            <select name="month" class="form-control">
                                                <option label="Choose One"></option>
                                                <option value="January">January</option>
                                                <option value="February">February</option>
                                                <option value="March">March</option>
                                                <option value="April">April</option>
                                                <option value="May">May</option>
                                                <option value="Jun">Jun</option>
                                                <option value="July">July</option>
                                                <option value="August">August</option>
                                                <option value="September">September</option>
                                                <option value="October">October</option>
                                                <option value="November">November</option>
                                                <option value="December">December</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <h5>Select Year <span class="text-danger">*</span></h5>
                                        <div class="controls">
                                            <select name="year_name" class="form-control">
                                                <option label="Choose One"></option>
                                                <option value="2020">2020</option>
                                                <option value="2021">2021</option>
                                                <option value="2022">2022</option>
                                                <option value="2023">2023</option>
                                                <option value="2024">2024</option>
                                                <option value="2025">2025</option>
                                                <option value="2026">2026</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="text-xs-right">
                                        <input type="button" class="btn btn-rounded btn-primary mb-5 " id='searchByMonthBtn'
                                            value="Search">
                                    </div>
                                </div>
                            </div>
                            <!-- /.box-body -->
                        </div>
                        <!-- /.box -->
                    </div>
                    <div class="col-4">
                        <div class="box">
                            <div class="box-header with-border">
                                <h3 class="box-title">Select Year </h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <div class="table-responsive">
                                    <div class="form-group">
                                        <h5>Select Year <span class="text-danger">*</span></h5>
                                        <div class="controls">
                                            <select name="year" class="form-control">
                                                <option label="Choose One"></option>
                                                <option value="2020">2020</option>
                                                <option value="2021">2021</option>
                                                <option value="2022">2022</option>
                                                <option value="2023">2023</option>
                                                <option value="2024">2024</option>
                                                <option value="2025">2025</option>
                                                <option value="2026">2026</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /.box-body -->
                        </div>
                        <!-- /.box -->
                    </div>
                    <!--   ------------End  Add Search Page -------- -->
                </div>
                <!-- /.row -->
                <div class="row">
                    <div class="col-12">
                        <div class="box">
                            <div class="box-header with-border">
                                <h3 class="box-title">Order List</h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <div class="table-responsive">
                                    <table id="report-table" class="table table-bordered table-striped">
                                        <thead>
                                            <tr>
                                                <th>No</th>
                                                <th>Date </th>
                                                <th>Invoice </th>
                                                <th>Amount </th>
                                                <th>Payment </th>
                                                <th>Status </th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tfoot></tfoot>
                                    </table>
                                </div>
                            </div>
                            <!-- /.box-body -->
                        </div>
                        <!-- /.box -->
                    </div>
                    <!-- /.col -->
                </div>
            </section>
        </div>
    </div>
@endsection
@push('scripts')
    <script src="{{ asset('backend/assets/vendor_components/datatable/datatables.min.js') }}"></script>
    <script>
        $(function() {
            let table = $('#report-table').DataTable({
                dom: 'Bfrtip',
                lengthMenu: [
                    [10, 25, 50, -1],
                    ['10 rows', '25 rows', '50 rows', 'Show all']
                ],
                buttons: [
                    'pageLength',
                ],
                processing: true,
                serverSide: true,
                ajax: "{{ route('admin.orders.index') }}",
                searchDelay: 500,
                lengthMenu: [10, 25, 50, 75, 100, 250, 500],
                columns: [{
                        data: 'DT_RowIndex',
                        name: 'id'
                    },
                    {
                        data: 'order_date',
                        name: 'order_date',

                        orderable: true,
                        searchable: true
                    },
                    {
                        data: 'invoice_no',
                        name: 'invoice_no',
                        orderable: true,
                    },
                    {
                        data: 'amount',
                        name: 'amount',
                        orderable: true,
                    },
                    {
                        data: 'payment_method',
                        name: 'payment_method',
                        orderable: true,
                    },
                    {
                        data: 'status',
                        name: 'status',
                        searchDelay: 500,
                    },
                    {
                        data: 'action',
                        name: 'action',
                        orderable: false,
                        searchable: false
                    },
                ]
            });

            $('.dt-buttons.btn-group').append(`
                <button class="btn btn-secondary buttons-reset" tabindex="0" aria-controls="orders-table">
                    <span><i class="fa fa-undo"></i> Reset</span>
                </button>
            `)

            $('.buttons-reset').on('click', function() {
                table.search('').clear().draw();
                table.ajax.reload();
            })


            $('#report-table_filter').parent().prepend(`
                <div class="d-inline pull-right pt-5">
                    <label>Sort by:</label>
                    <select class="form-control d-inline" style="width: inherit;" id='sortByStatus'>
                        <option value='' >---Select status---</option>
                        <option value='pending' >Pending</option>
                        <option value='confirm'>Confirm</option>
                        <option value='processing'>Processing</option>
                        <option value='picked'>Picked</option>
                        <option value='shipped'>Shipped</option>
                        <option value='delivered'>Delivered</option>
                        <option value='cancel'>Cancel</option>
                    </select>
                </div>
            `)

            $('#sortByStatus').on('change', function() {
                table.search(this.value).draw();
            })

            $('#date').on('change', function() {
                table.search(formatDatedFY(this.value)).draw();
            })

            $('select[name=year]').on('change', function() {
                table.search(this.value).draw();
            })

            $('#searchByMonthBtn').click(function() {
                let month = $('select[name=month]').val()
                let yearName = $('select[name=year_name]').val()
                let searchVal = `${month} ${yearName}`
                table.search(searchVal).draw();
            })
        })
    </script>
@endpush