routes/admin.php
<?php

use App\Http\Controllers\Admin\{
    AdminAuthenticatedSessionController,
    AdminController,
    BrandController,
    CategoryController,
    CountryController,
    CouponController,
    DashboardController,
    HomeProductCategoryController,
    OrderController,
    PasswordController,
    PermissionController,
    PostCategoryController,
    PostController,
    ProductController,
    ProductImageController,
    ProductStockController,
    ProfileInformationController,
    ReportController,
    ReviewController,
    RoleController,
    SeoSettingController,
    SiteSettingController,
    SliderController,
    UserController,
};
use Illuminate\Support\Facades\Route;


Route::prefix('admin')->group(function () {
    Route::middleware('guest:admin')->group(function () {
        Route::view('/', 'pages.admin.login');
        Route::view('/login', 'pages.admin.login');
        Route::post('/login', [AdminAuthenticatedSessionController::class, 'store'])->name('login');
    });

    Route::group([
        'middleware' => ['auth:sanctum,admin', 'verified', 'auth:admin'],
    ], function () {
        Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

        Route::view('/profile', 'profile.admin.show')->name('profile.show');
        Route::put('/profile-information', [ProfileInformationController::class, 'update'])->name('profile-information.update');
        Route::put('/password', [PasswordController::class, 'update'])->name('password.update');

        Route::resource('brands', BrandController::class)->except(['create', 'show']);
        Route::resource('categories', CategoryController::class)->except(['create', 'show']);

        Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
            Route::get('/toggle-status/{product}', [ProductController::class, 'toggleStatus'])->name('toggle-status');
            Route::get('/images/{image}/delete', [ProductImageController::class, 'deleteProductImage'])->name('image.delete');
            Route::resource('images', ProductImageController::class)->only(['store'])->names(['store' => 'images.update']);
            Route::resource('stock', ProductStockController::class)->only(['index'])->names(['index' => 'stock.list']);
            Route::post('/import-data',[ProductController::class,'importData'])->name('import-data');
            Route::get('delete-all',function(){
                DB::table('products')->delete();
            return back()->with('success','table cleared.');
            })->name('delete-all');
        });
        Route::resource('products', ProductController::class)->except(['show']);

        Route::get('/coupons/toggle-status/{coupon}', [CouponController::class, 'toggleStatus'])->name('coupons.toggle-status');
        Route::resource('coupons', CouponController::class)->except(['show', 'create']);
        Route::resource('countries', CountryController::class)->except(['create', 'show']);
        
        Route::get('/sliders/toggle-status/{slider}', [SliderController::class, 'toggleStatus'])->name('sliders.toggle-status');
        Route::resource('sliders', SliderController::class)->except(['create', 'show']);

        Route::resource('home-category',HomeProductCategoryController::class)->only(['update','index'])->names([
            'index' => 'product.category.tabs',
            'update' => 'product.category.update',
        ]);

        Route::get('/orders/updateStatus/{order}', [OrderController::class, 'updateStatus'])->name('orders.updateStatus');
        Route::get('/return-orders/{order}/approve', [OrderController::class, 'returnApprove'])->name('return.order.approve');
        Route::get('/invoice/{order}/download', [OrderController::class, 'invoiceDownload'])->name('order.invoice.download');
        Route::resource('orders',OrderController::class)->only(['index','show']);


        Route::get('/reports', [ReportController::class, 'index'])->name('reports.index');

        Route::resource('users', UserController::class)->only(['index']);

        Route::group(['prefix' => 'blog', 'as' => 'blog.'], function () {
            Route::resource('postCategories', PostCategoryController::class)->except(['show', 'create']);
            Route::resource('posts', PostController::class)->except(['show']);
        });

        Route::group(['as' => 'settings.'], function () {
            Route::resource('siteSetting', SiteSettingController::class)->only(['edit', 'update']);
            Route::resource('seoSetting', SeoSettingController::class)->only(['edit', 'update']);
        });

        Route::get('/reviews/{review}/approve', [ReviewController::class, 'approve'])->name('reviews.approve');
        Route::resource('reviews', ReviewController::class)->only('index', 'destroy');

        Route::resource('roles', RoleController::class)->except(['create', 'show']);
        Route::resource('permissions', PermissionController::class)->except(['create', 'show']);

        Route::resource('admins', AdminController::class);

        Route::view('/menu', 'pages.admin.menu')->name('menu');

        Route::post('/logout', [AdminAuthenticatedSessionController::class, 'destroy'])->name('logout');
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\{
    EmailVerificationController,
    FrontendController,
};
use App\Http\Controllers\Frontend\ProductDetailController;
use App\Http\Controllers\User\{
    OrderController,
    ReviewController,
    ProfileInformationController,
    CheckoutController,
    CartController,
    CartCouponController,
    PasswordController,
    UserController,
    WishlistController,
};
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']
], function () {
    Route::get('/', [FrontendController::class, 'home'])->name('home');
    Route::get('/details/{slug}', [ProductDetailController::class, 'show'])->name('product.details');
    Route::get('/product/tag/{tag}', [FrontendController::class, 'fetchProductByTag'])->name('product.tag');
    Route::get('/category/{slug}', [FrontendController::class, 'fetchProductByCategory'])->name('product.category');
    Route::get('/product/modal/{product}', [FrontendController::class, 'addToCartModal'])->name('product.modal');

    Route::get('/shop', [FrontendController::class, 'viewShop'])->name('shop');

    Route::group(['prefix' => 'carts', 'as' => 'carts.'], function () {
        Route::resource('coupon', CartCouponController::class)->only(['store', 'destroy']);
        Route::get('/mini-cart', [CartController::class, 'getMiniCart'])->name('mini.cart');
    });
    Route::resource('carts', CartController::class)->except(['create', 'edit'])->names(['show' => 'carts.details']);

    Route::get('/products/search', [FrontendController::class, 'productSearch'])->name('products.search');
    Route::post('/products/search-dropdown', [FrontendController::class, 'productSearchDropdown'])->name('products.search-dropdown');

    Route::group(['prefix' => 'blog', 'as' => 'blog.'], function () {
        Route::get('/', [FrontendController::class, 'blogList'])->name('index');
        Route::get('/{slug}/{id}/details', [FrontendController::class, 'blogDetails'])->name('details');
        Route::get('/{post_category}/category', [FrontendController::class, 'blogPostCategory'])->name('post.category');
    });

    Route::resource('wishlist', WishlistController::class)->only(['index', 'store', 'destroy']);

    Route::group(['middleware' => ['auth', 'user']], function () {
        Route::group(['middleware' => ['verified'], 'prefix' => 'user', 'as' => 'user.'], function () {
            Route::view('/', 'dashboard');
            Route::view('/dashboard', 'dashboard')->name('dashboard');

            Route::view('/profile', 'profile.show')->name('profile.show');
            Route::put('/profile-information', [ProfileInformationController::class, 'update'])->name('profile.update');
            Route::put('/password', [PasswordController::class, 'update'])->name('password.update');

            Route::post('reviews', [ReviewController::class, 'store'])->name('reviews.store');

            Route::resource('checkout', CheckoutController::class)->only(['index', 'store'])->names(['index' => 'checkout.view']);

            Route::group(['prefix' => 'orders'], function () {
                Route::get('/invoice/{order}/download', [OrderController::class, 'download'])->name('order.invoice.download');
                Route::get('/tracking', [OrderController::class, 'tracking'])->name('order.tracking');
                Route::post('/{order}/return', [OrderController::class, 'returnOrderRequest'])->name('order.return');
            });
            Route::resource('orders', OrderController::class)->only(['index', 'show']);
        });

        Route::group(['prefix' => 'email'], function () {
            Route::get('/verify/{id}/{hash}', [EmailVerificationController::class, 'handler'])->middleware(['signed'])->name('verification.verify');
            Route::view('/verify', 'auth.verify-email')->name('verification.notice');
            Route::post('/verification-notification', [EmailVerificationController::class, 'resend'])->middleware(['throttle:6,1'])->name('verification.send');
        });

        Route::post('/logout', [UserController::class, 'logout'])->name('logout');
    });
});

resources/views/pages/admin/blog/category_edit.blade.php
@extends('layouts.admin.master')
@section('title', 'Post Category Edit')

@section('content')
    <div class="content-wrapper">
        <div class="container-full">
            <div class="content-header">
                <div class="d-flex align-items-center">
                    <div class="mr-auto">
                        <div class="d-inline-block align-items-center">
                            <nav>
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}"><i
                                                class="mdi mdi-home-outline"></i></a></li>
                                    <li class="breadcrumb-item" aria-current="page">
                                        <a href="{{ route('admin.blog.postCategories.index') }}">Post Category All</a>
                                    </li>
                                    <li class="breadcrumb-item active" aria-current="page">Edit</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <section class="content">
                <div class="row">
                    <div class="col-md-12">
                        <div class="box">
                            <div class="box box-widget widget-user p-5">
                                <h3>Edit Post Category</h3>
                                <!-- Add the bg color to the header using any of the bg-* classes -->
                                <form method='post' action="{{ route('admin.blog.postCategories.update', $postCategory->id) }}"
                                    enctype="multipart/form-data">
                                    @csrf
                                    @method('put')
                                    @foreach (LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
                                        <div class="form-group @error("name.$localeCode") is-invalid @enderror">
                                            <h5>Category Name {{ $properties['native'] }} <span
                                                    class="text-danger">*</span>
                                            </h5>
                                            <div class="controls">
                                                <input type="text" name="name[{{ $localeCode }}]"
                                                    value="{{ $postCategory->getTranslation('name',$localeCode) }}" class="form-control">
                                            </div>

                                            @error("name.$localeCode")
                                                <div class="text-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    @endforeach

                                    @foreach (LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
                                        <div class="form-group @error("slug.$localeCode") is-invalid @enderror">
                                            <h5>Category Slug {{ $properties["native"] }} <span
                                                    class="text-danger">*</span>
                                            </h5>
                                            <div class="controls">
                                                <input type="text" name="slug[{{ $localeCode }}]"
                                                    value="{{ $postCategory->getTranslation('slug',$localeCode) }}" class="form-control">
                                            </div>
                                            @error("slug.$localeCode")
                                                <div class="text-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    @endforeach
                                    <div class="text-xs-right">
                                        <button type="submit"
                                            class="btn btn-rounded btn-primary mb-5 pull-right">Submit</button>
                                    </div>
                                </form>
                            </div>
                            <!-- /.box-body -->
                        </div>
                    </div>
                    <!-- /.box -->
                </div>
            </section>
        </div>
    </div>
@endsection

resources/views/pages/admin/blog/post_create.blade.php
@extends('layouts.admin.master')
@section('title', 'Post Create')
@section('content')
    <div class="content-wrapper">
        <div class="container-full">
            <div class="content-header">
                <div class="d-flex align-items-center">
                    <div class="mr-auto">
                        <div class="d-inline-block align-items-center">
                            <nav>
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}"><i
                                                class="mdi mdi-home-outline"></i></a></li>
                                    <li class="breadcrumb-item">
                                        <a href="{{ route('admin.blog.posts.index') }}">All Blog Post</a>
                                    </li>
                                    <li class="breadcrumb-item active" aria-current="page">Post Create</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <section class="content">
                <!-- Basic Forms -->
                <div class="box">
                    <div class="box-header with-border">
                        <h4 class="box-title">Add Post </h4>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="row">
                            <div class="col">
                                <form method="post" action="{{ route('admin.blog.posts.store') }}"
                                    enctype="multipart/form-data">
                                    @csrf
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="row">
                                                <!-- start 1st row  -->
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <div class="form-group">
                                                            <h5>Image <span class="text-danger">*</span></h5>
                                                            <div class="controls">
                                                                <input type="file" name="image" class="form-control"
                                                                    onChange="imageUrl(this)">
                                                                @error('image')
                                                                    <span class="text-danger">{{ $message }}</span>
                                                                @enderror
                                                                <img src="" id="image">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div> <!-- end col md 4 -->
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <h5>Post Category Select <span class="text-danger">*</span></h5>
                                                        <div class="controls">
                                                            <select name="post_category_id" class="form-control">
                                                                @foreach ($postCategories as $postCategory)
                                                                    <option value="{{ $postCategory['id'] }}"
                                                                        @if (old('post_category_id') === $postCategory['name']) selected @endif>
                                                                        {{ $postCategory['name'] }}
                                                                    </option>
                                                                @endforeach
                                                            </select>
                                                            @error('post_category_id')
                                                                <span class="text-danger">{{ $message }}</span>
                                                            @enderror
                                                        </div>
                                                    </div>
                                                </div> <!-- end col md 4 -->
                                            </div> <!-- end 1st row  -->
                                            <div class="row">
                                                <!-- start 2nd row  -->
                                                @foreach (LaravelLocalization::getSupportedLocales() as $localeCode => $lang)
                                                    <div class="col-md-4">
                                                        <div class="form-group">
                                                            <h5>Post Title {{ $lang['name'] }} <span
                                                                    class="text-danger">*</span></h5>
                                                            <div class="controls">
                                                                <input type="text" name="title[{{ $localeCode }}]"
                                                                    class="form-control"
                                                                    value="{{ old("title.$localeCode") }}" />
                                                                @error("title.$localeCode")
                                                                    <span class="text-danger">{{ $message }}</span>
                                                                @enderror
                                                            </div>
                                                        </div>
                                                    </div> <!-- end col md 4 -->
                                                @endforeach
                                                @foreach (LaravelLocalization::getSupportedLocales() as $localeCode => $lang)
                                                    <div class="col-md-4">
                                                        <div class="form-group">
                                                            <h5>Post Slug<span class="text-danger">*</span></h5>
                                                            <div class="controls">
                                                                <input type="text" name="slug[{{ $localeCode }}]"
                                                                    value="{{ old("slug.$localeCode") }}"
                                                                    class="form-control">
                                                                @error("slug.$localeCode")
                                                                    <span class="text-danger">{{ $message }}</span>
                                                                @enderror
                                                            </div>
                                                        </div>
                                                    </div> <!-- end col md 4 -->
                                                @endforeach
                                            </div> <!-- end 2nd row  -->
                                            <div class="row">
                                                <!-- start 7th row  -->
                                                @foreach (LaravelLocalization::getSupportedLocales() as $localeCode => $lang)
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <h5>Details {{ $lang['name'] }} <span
                                                                    class="text-danger">*</span>
                                                            </h5>
                                                            <div class="controls">
                                                                <textarea name="details[{{ $localeCode }}]"
                                                                    value="{{ old("details.$localeCode") }}"
                                                                    class="form-control textarea" required
                                                                    placeholder="Textarea text">
                                                                            {{ old("details.$localeCode") }}
                                                                            </textarea>
                                                                @error("details.$localeCode")
                                                                    <span class="text-danger">{{ $message }}</span>
                                                                @enderror
                                                            </div>
                                                        </div>
                                                    </div> <!-- end col md 6 -->
                                                @endforeach
                                            </div> <!-- end 7th row  -->
                                            <hr>
                                            <div class="text-xs-right">
                                                <input type="submit" class="btn btn-rounded btn-primary mb-5"
                                                    value="Add Post">
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <!-- /.col -->
                        </div>
                        <!-- /.row -->
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </section>
            <!-- /.content -->
        </div>
    </div>
@endsection
@push('scripts')
    {{-- <script src="{{ asset('backend/assets/vendor_components/ckeditor/ckeditor.js') }}"></script> --}}
    <script src="{{ asset('backend/assets/vendor_components/ckeditor_4.16.2_501b131964df/ckeditor.js') }}"></script>
    <script type="text/javascript">
        function imageUrl(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function(e) {
                    $('#image').attr('src', e.target.result).width(80).height(80);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
    <script>
        $(document).ready(function() {
            CKEDITOR.replaceAll('textarea');
            $('.textarea').ckeditor();
            $('#multiImg').on('change', function() { //on file input change
                if (window.File && window.FileReader && window.FileList && window
                    .Blob) //check File API supported browser
                {
                    var data = $(this)[0].files; //this file data
                    $.each(data, function(index, file) { //loop though each file
                        if (/(\.|\/)(gif|jpe?g|png)$/i.test(file
                                .type)) { //check supported file type
                            var fRead = new FileReader(); //new filereader
                            fRead.onload = (function(file) { //trigger function on successful read
                                return function(e) {
                                    var img = $('<img/>').addClass('thumb').attr('src',
                                            e.target.result).width(80)
                                        .height(80); //create image element
                                    $('#preview_img').append(
                                        img); //append image to output element
                                };
                            })(file);
                            fRead.readAsDataURL(file); //URL representing the file's data.
                        }
                    });
                } else {
                    alert("Your browser doesn't support File API!"); //if File API is absent
                }
            });
        });
    </script>
@endpush

resources/views/pages/admin/blog/post_index.blade.php
@extends('layouts.admin.master')
@section('title', 'All Blog Post')
@section('content')
    <div class="content-wrapper">
        <div class="container-full">
            <div class="content-header">
                <div class="d-flex align-items-center">
                    <div class="mr-auto">
                        <div class="d-inline-block align-items-center">
                            <nav>
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}"><i
                                                class="mdi mdi-home-outline"></i></a></li>
                                    <li class="breadcrumb-item" aria-current="page">
                                        Admin
                                    </li>
                                    <li class="breadcrumb-item active" aria-current="page">All Blog Post</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <section class="content">
                <div class="row">
                    <div class="col-12">
                        <div class="box">
                            <div class="box-header with-border">
                                <h3 class="box-title">Post List </h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <div class="table-responsive">
                                    {{ $dataTable->table([], true) }}
                                </div>
                            </div>
                            <!-- /.box-body -->
                        </div>
                        <!-- /.box -->
                    </div>
                    <!-- /.col -->
                </div>
        </div>
    </div>
    <!-- /.row -->
    </section>
    <!-- /.content -->
    </div>
    </div>
@endsection
@push('scripts')
    {!! $dataTable->scripts() !!}
@endpush