routes/admin.php
<?php

use App\Http\Controllers\Admin\{
    AdminAuthenticatedSessionController,
    AdminController,
    BrandController,
    CategoryController,
    CountryController,
    CouponController,
    DashboardController,
    HomeProductCategoryController,
    OrderController,
    PasswordController,
    PermissionController,
    PostCategoryController,
    PostController,
    ProductController,
    ProductImageController,
    ProductStockController,
    ProfileInformationController,
    ReportController,
    ReviewController,
    RoleController,
    SeoSettingController,
    SiteSettingController,
    SliderController,
    UserController,
};
use Illuminate\Support\Facades\Route;


Route::prefix('admin')->group(function () {
    Route::middleware('guest:admin')->group(function () {
        Route::view('/', 'pages.admin.login');
        Route::view('/login', 'pages.admin.login');
        Route::post('/login', [AdminAuthenticatedSessionController::class, 'store'])->name('login');
    });

    Route::group([
        'middleware' => ['auth:sanctum,admin', 'verified', 'auth:admin'],
    ], function () {
        Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

        Route::view('/profile', 'profile.admin.show')->name('profile.show');
        Route::put('/profile-information', [ProfileInformationController::class, 'update'])->name('profile-information.update');
        Route::put('/password', [PasswordController::class, 'update'])->name('password.update');

        Route::resource('brands', BrandController::class)->except(['create', 'show']);
        Route::resource('categories', CategoryController::class)->except(['create', 'show']);

        Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
            Route::get('/toggle-status/{product}', [ProductController::class, 'toggleStatus'])->name('toggle-status');
            Route::get('/images/{image}/delete', [ProductImageController::class, 'deleteProductImage'])->name('image.delete');
            Route::resource('images', ProductImageController::class)->only(['store'])->names(['store' => 'images.update']);
            Route::resource('stock', ProductStockController::class)->only(['index'])->names(['index' => 'stock.list']);
            Route::post('/import-data',[ProductController::class,'importData'])->name('import-data');
            Route::get('delete-all',function(){
                DB::table('products')->delete();
            return back()->with('success','table cleared.');
            })->name('delete-all');
        });
        Route::resource('products', ProductController::class)->except(['show']);

        Route::get('/coupons/toggle-status/{coupon}', [CouponController::class, 'toggleStatus'])->name('coupons.toggle-status');
        Route::resource('coupons', CouponController::class)->except(['show', 'create']);
        Route::resource('countries', CountryController::class)->except(['create', 'show']);
        
        Route::get('/sliders/toggle-status/{slider}', [SliderController::class, 'toggleStatus'])->name('sliders.toggle-status');
        Route::resource('sliders', SliderController::class)->except(['create', 'show']);

        Route::resource('home-category',HomeProductCategoryController::class)->only(['update','index'])->names([
            'index' => 'product.category.tabs',
            'update' => 'product.category.update',
        ]);

        Route::get('/orders/updateStatus/{order}', [OrderController::class, 'updateStatus'])->name('orders.updateStatus');
        Route::get('/return-orders/{order}/approve', [OrderController::class, 'returnApprove'])->name('return.order.approve');
        Route::get('/invoice/{order}/download', [OrderController::class, 'invoiceDownload'])->name('order.invoice.download');
        Route::resource('orders',OrderController::class)->only(['index','show']);


        Route::get('/reports', [ReportController::class, 'index'])->name('reports.index');

        Route::resource('users', UserController::class)->only(['index']);

        Route::group(['prefix' => 'blog', 'as' => 'blog.'], function () {
            Route::resource('postCategories', PostCategoryController::class)->except(['show', 'create']);
            Route::resource('posts', PostController::class)->except(['show']);
        });

        Route::group(['as' => 'settings.'], function () {
            Route::resource('siteSetting', SiteSettingController::class)->only(['edit', 'update']);
            Route::resource('seoSetting', SeoSettingController::class)->only(['edit', 'update']);
        });

        Route::get('/reviews/{review}/approve', [ReviewController::class, 'approve'])->name('reviews.approve');
        Route::resource('reviews', ReviewController::class)->only('index', 'destroy');

        Route::resource('roles', RoleController::class)->except(['create', 'show']);
        Route::resource('permissions', PermissionController::class)->except(['create', 'show']);

        Route::resource('admins', AdminController::class);

        Route::view('/menu', 'pages.admin.menu')->name('menu');

        Route::post('/logout', [AdminAuthenticatedSessionController::class, 'destroy'])->name('logout');
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\{
    EmailVerificationController,
    FrontendController,
};
use App\Http\Controllers\Frontend\ProductDetailController;
use App\Http\Controllers\User\{
    OrderController,
    ReviewController,
    ProfileInformationController,
    CheckoutController,
    CartController,
    CartCouponController,
    PasswordController,
    UserController,
    WishlistController,
};
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']
], function () {
    Route::get('/', [FrontendController::class, 'home'])->name('home');
    Route::get('/details/{slug}', [ProductDetailController::class, 'show'])->name('product.details');
    Route::get('/product/tag/{tag}', [FrontendController::class, 'fetchProductByTag'])->name('product.tag');
    Route::get('/category/{slug}', [FrontendController::class, 'fetchProductByCategory'])->name('product.category');
    Route::get('/product/modal/{product}', [FrontendController::class, 'addToCartModal'])->name('product.modal');

    Route::get('/shop', [FrontendController::class, 'viewShop'])->name('shop');

    Route::group(['prefix' => 'carts', 'as' => 'carts.'], function () {
        Route::resource('coupon', CartCouponController::class)->only(['store', 'destroy']);
        Route::get('/mini-cart', [CartController::class, 'getMiniCart'])->name('mini.cart');
    });
    Route::resource('carts', CartController::class)->except(['create', 'edit'])->names(['show' => 'carts.details']);

    Route::get('/products/search', [FrontendController::class, 'productSearch'])->name('products.search');
    Route::post('/products/search-dropdown', [FrontendController::class, 'productSearchDropdown'])->name('products.search-dropdown');

    Route::group(['prefix' => 'blog', 'as' => 'blog.'], function () {
        Route::get('/', [FrontendController::class, 'blogList'])->name('index');
        Route::get('/{slug}/{id}/details', [FrontendController::class, 'blogDetails'])->name('details');
        Route::get('/{post_category}/category', [FrontendController::class, 'blogPostCategory'])->name('post.category');
    });

    Route::resource('wishlist', WishlistController::class)->only(['index', 'store', 'destroy']);

    Route::group(['middleware' => ['auth', 'user']], function () {
        Route::group(['middleware' => ['verified'], 'prefix' => 'user', 'as' => 'user.'], function () {
            Route::view('/', 'dashboard');
            Route::view('/dashboard', 'dashboard')->name('dashboard');

            Route::view('/profile', 'profile.show')->name('profile.show');
            Route::put('/profile-information', [ProfileInformationController::class, 'update'])->name('profile.update');
            Route::put('/password', [PasswordController::class, 'update'])->name('password.update');

            Route::post('reviews', [ReviewController::class, 'store'])->name('reviews.store');

            Route::resource('checkout', CheckoutController::class)->only(['index', 'store'])->names(['index' => 'checkout.view']);

            Route::group(['prefix' => 'orders'], function () {
                Route::get('/invoice/{order}/download', [OrderController::class, 'download'])->name('order.invoice.download');
                Route::get('/tracking', [OrderController::class, 'tracking'])->name('order.tracking');
                Route::post('/{order}/return', [OrderController::class, 'returnOrderRequest'])->name('order.return');
            });
            Route::resource('orders', OrderController::class)->only(['index', 'show']);
        });

        Route::group(['prefix' => 'email'], function () {
            Route::get('/verify/{id}/{hash}', [EmailVerificationController::class, 'handler'])->middleware(['signed'])->name('verification.verify');
            Route::view('/verify', 'auth.verify-email')->name('verification.notice');
            Route::post('/verification-notification', [EmailVerificationController::class, 'resend'])->middleware(['throttle:6,1'])->name('verification.send');
        });

        Route::post('/logout', [UserController::class, 'logout'])->name('logout');
    });
});

app/Http/Controllers/Admin/PermissionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\DataTables\PermissionsDataTable;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Permission;

class PermissionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(PermissionsDataTable $dataTable)
    {
        return $dataTable->render('pages.admin.permission.index');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create permissions');
        $validated = $request->validate(['name' => 'required|unique:permissions,name|max:100']);
        Permission::create($validated);
        return back()->with('success', 'Permission has been created successfully!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \Spatie\Permission\Models\Permission $permission
     * @return \Illuminate\Http\Response
     */
    public function edit(Permission $permission)
    {
        return view('pages.admin.permission.edit', compact('permission'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Spatie\Permission\Models\Permission $permission
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Permission $permission)
    {
        $this->authorize('update permissions');
        $validated = $request->validate(['name' => 'required|max:100']);
        $permission->update($validated);
        return back()->with('success', 'Permission has been updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \Spatie\Permission\Models\Permission $permission
     * @return \Illuminate\Http\Response
     */
    public function destroy(Permission $permission)
    {
        $this->authorize('delete permissions');
        $permission->delete();
        return back()->with('success', 'Permission has been deleted successfully!');
    }
}

resources/views/pages/admin/permission/edit.blade.php
@extends('layouts.admin.master')
@section('title', 'Edit Permission')

@section('content')
    <div class="content-wrapper">
        <div class="container-full">
            <div class="content-header">
                <div class="d-flex align-items-center">
                    <div class="mr-auto">
                        <div class="d-inline-block align-items-center">
                            <nav>
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}"><i
                                                class="mdi mdi-home-outline"></i></a></li>
                                    <li class="breadcrumb-item" aria-current="page">
                                        <a href="{{ route('admin.permissions.index') }}">All Permission</a>
                                    </li>
                                    <li class="breadcrumb-item active" aria-current="page">Edit</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <section class="content">
                <div class="row">
                    <div class="col-md-12">
                        <div class="box">
                            <!-- /.box-header -->
                            <div class="box-widget widget-user p-5">
                                <h3>Edit Permission</h3>
                                <!-- Add the bg color to the header using any of the bg-* classes -->
                                <form method='post' action="{{ route('admin.permissions.update', $permission->id) }}">
                                    @csrf
                                    @method('put')
                                    <div class="form-group @error('name') is-invalid @enderror">
                                        <h5>Name <span class="text-danger">*</span></h5>
                                        <div class="controls">
                                            <input type="text" name="name" value="{{ $permission->name }}"
                                                class="form-control">
                                        </div>
                                        @error('name')
                                            <div class="text-danger">{{ $message }}</div>
                                        @enderror
                                    </div>
                                    <div class="text-xs-right">
                                        <button type="submit"
                                            class="btn btn-rounded btn-primary mb-5 pull-right">Submit</button>
                                    </div>
                                </form>
                            </div>
                            <!-- /.box-body -->
                        </div>
                    </div>
                    <!-- /.box -->
                </div>
            </section>
        </div>
    </div>
@endsection

resources/views/pages/admin/permission/index.blade.php
@extends('layouts.admin.master')
@section('title', 'Permission Management')

@section('content')
    <div class="content-wrapper">
        <div class="container-full">
            <div class="content-header">
                <div class="d-flex align-items-center">
                    <div class="mr-auto">
                        <div class="d-inline-block align-items-center">
                            <nav>
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}"><i
                                                class="mdi mdi-home-outline"></i></a></li>
                                    <li class="breadcrumb-item" aria-current="page">
                                        Admin
                                    </li>
                                    <li class="breadcrumb-item active" aria-current="page">All Permission</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <section class="content">
                <div class="row">
                    <div class="col-md-8">
                        <div class="box">
                            <div class="box-body">
                                <div class="table-responsive">
                                    {{ $dataTable->table([], true) }}
                                </div>
                            </div>
                            <!-- /.box-body -->
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="box">
                            <div class="box box-widget widget-user p-5">
                                <h3>Add Permission</h3>
                                <!-- Add the bg color to the header using any of the bg-* classes -->
                                <form method='post' action="{{ route('admin.permissions.store') }}">
                                    @csrf
                                    <div class="form-group @error('name') is-invalid @enderror">
                                        <h5>Name<span class="text-danger">*</span></h5>
                                        <div class="controls">
                                            <input type="text" name="name" class="form-control">
                                        </div>
                                        @error('name')
                                            <div class="text-danger">{{ $message }}</div>
                                        @enderror
                                    </div>
                                    <div class="text-xs-right">
                                        <button type="submit"
                                            class="btn btn-rounded btn-primary mb-5 pull-right">Submit</button>
                                    </div>
                                </form>
                            </div>
                            <!-- /.box-body -->
                        </div>
                    </div>
                    <!-- /.box -->
                </div>
            </section>
        </div>
    </div>
@endsection
@push('scripts')
    {!! $dataTable->scripts() !!}
@endpush