routes/admin.php
<?php

use App\Http\Controllers\Admin\{
    AdminAuthenticatedSessionController,
    AdminController,
    BrandController,
    CategoryController,
    CountryController,
    CouponController,
    DashboardController,
    HomeProductCategoryController,
    OrderController,
    PasswordController,
    PermissionController,
    PostCategoryController,
    PostController,
    ProductController,
    ProductImageController,
    ProductStockController,
    ProfileInformationController,
    ReportController,
    ReviewController,
    RoleController,
    SeoSettingController,
    SiteSettingController,
    SliderController,
    UserController,
};
use Illuminate\Support\Facades\Route;


Route::prefix('admin')->group(function () {
    Route::middleware('guest:admin')->group(function () {
        Route::view('/', 'pages.admin.login');
        Route::view('/login', 'pages.admin.login');
        Route::post('/login', [AdminAuthenticatedSessionController::class, 'store'])->name('login');
    });

    Route::group([
        'middleware' => ['auth:sanctum,admin', 'verified', 'auth:admin'],
    ], function () {
        Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

        Route::view('/profile', 'profile.admin.show')->name('profile.show');
        Route::put('/profile-information', [ProfileInformationController::class, 'update'])->name('profile-information.update');
        Route::put('/password', [PasswordController::class, 'update'])->name('password.update');

        Route::resource('brands', BrandController::class)->except(['create', 'show']);
        Route::resource('categories', CategoryController::class)->except(['create', 'show']);

        Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
            Route::get('/toggle-status/{product}', [ProductController::class, 'toggleStatus'])->name('toggle-status');
            Route::get('/images/{image}/delete', [ProductImageController::class, 'deleteProductImage'])->name('image.delete');
            Route::resource('images', ProductImageController::class)->only(['store'])->names(['store' => 'images.update']);
            Route::resource('stock', ProductStockController::class)->only(['index'])->names(['index' => 'stock.list']);
            Route::post('/import-data',[ProductController::class,'importData'])->name('import-data');
            Route::get('delete-all',function(){
                DB::table('products')->delete();
            return back()->with('success','table cleared.');
            })->name('delete-all');
        });
        Route::resource('products', ProductController::class)->except(['show']);

        Route::get('/coupons/toggle-status/{coupon}', [CouponController::class, 'toggleStatus'])->name('coupons.toggle-status');
        Route::resource('coupons', CouponController::class)->except(['show', 'create']);
        Route::resource('countries', CountryController::class)->except(['create', 'show']);
        
        Route::get('/sliders/toggle-status/{slider}', [SliderController::class, 'toggleStatus'])->name('sliders.toggle-status');
        Route::resource('sliders', SliderController::class)->except(['create', 'show']);

        Route::resource('home-category',HomeProductCategoryController::class)->only(['update','index'])->names([
            'index' => 'product.category.tabs',
            'update' => 'product.category.update',
        ]);

        Route::get('/orders/updateStatus/{order}', [OrderController::class, 'updateStatus'])->name('orders.updateStatus');
        Route::get('/return-orders/{order}/approve', [OrderController::class, 'returnApprove'])->name('return.order.approve');
        Route::get('/invoice/{order}/download', [OrderController::class, 'invoiceDownload'])->name('order.invoice.download');
        Route::resource('orders',OrderController::class)->only(['index','show']);


        Route::get('/reports', [ReportController::class, 'index'])->name('reports.index');

        Route::resource('users', UserController::class)->only(['index']);

        Route::group(['prefix' => 'blog', 'as' => 'blog.'], function () {
            Route::resource('postCategories', PostCategoryController::class)->except(['show', 'create']);
            Route::resource('posts', PostController::class)->except(['show']);
        });

        Route::group(['as' => 'settings.'], function () {
            Route::resource('siteSetting', SiteSettingController::class)->only(['edit', 'update']);
            Route::resource('seoSetting', SeoSettingController::class)->only(['edit', 'update']);
        });

        Route::get('/reviews/{review}/approve', [ReviewController::class, 'approve'])->name('reviews.approve');
        Route::resource('reviews', ReviewController::class)->only('index', 'destroy');

        Route::resource('roles', RoleController::class)->except(['create', 'show']);
        Route::resource('permissions', PermissionController::class)->except(['create', 'show']);

        Route::resource('admins', AdminController::class);

        Route::view('/menu', 'pages.admin.menu')->name('menu');

        Route::post('/logout', [AdminAuthenticatedSessionController::class, 'destroy'])->name('logout');
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\{
    EmailVerificationController,
    FrontendController,
};
use App\Http\Controllers\Frontend\ProductDetailController;
use App\Http\Controllers\User\{
    OrderController,
    ReviewController,
    ProfileInformationController,
    CheckoutController,
    CartController,
    CartCouponController,
    PasswordController,
    UserController,
    WishlistController,
};
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']
], function () {
    Route::get('/', [FrontendController::class, 'home'])->name('home');
    Route::get('/details/{slug}', [ProductDetailController::class, 'show'])->name('product.details');
    Route::get('/product/tag/{tag}', [FrontendController::class, 'fetchProductByTag'])->name('product.tag');
    Route::get('/category/{slug}', [FrontendController::class, 'fetchProductByCategory'])->name('product.category');
    Route::get('/product/modal/{product}', [FrontendController::class, 'addToCartModal'])->name('product.modal');

    Route::get('/shop', [FrontendController::class, 'viewShop'])->name('shop');

    Route::group(['prefix' => 'carts', 'as' => 'carts.'], function () {
        Route::resource('coupon', CartCouponController::class)->only(['store', 'destroy']);
        Route::get('/mini-cart', [CartController::class, 'getMiniCart'])->name('mini.cart');
    });
    Route::resource('carts', CartController::class)->except(['create', 'edit'])->names(['show' => 'carts.details']);

    Route::get('/products/search', [FrontendController::class, 'productSearch'])->name('products.search');
    Route::post('/products/search-dropdown', [FrontendController::class, 'productSearchDropdown'])->name('products.search-dropdown');

    Route::group(['prefix' => 'blog', 'as' => 'blog.'], function () {
        Route::get('/', [FrontendController::class, 'blogList'])->name('index');
        Route::get('/{slug}/{id}/details', [FrontendController::class, 'blogDetails'])->name('details');
        Route::get('/{post_category}/category', [FrontendController::class, 'blogPostCategory'])->name('post.category');
    });

    Route::resource('wishlist', WishlistController::class)->only(['index', 'store', 'destroy']);

    Route::group(['middleware' => ['auth', 'user']], function () {
        Route::group(['middleware' => ['verified'], 'prefix' => 'user', 'as' => 'user.'], function () {
            Route::view('/', 'dashboard');
            Route::view('/dashboard', 'dashboard')->name('dashboard');

            Route::view('/profile', 'profile.show')->name('profile.show');
            Route::put('/profile-information', [ProfileInformationController::class, 'update'])->name('profile.update');
            Route::put('/password', [PasswordController::class, 'update'])->name('password.update');

            Route::post('reviews', [ReviewController::class, 'store'])->name('reviews.store');

            Route::resource('checkout', CheckoutController::class)->only(['index', 'store'])->names(['index' => 'checkout.view']);

            Route::group(['prefix' => 'orders'], function () {
                Route::get('/invoice/{order}/download', [OrderController::class, 'download'])->name('order.invoice.download');
                Route::get('/tracking', [OrderController::class, 'tracking'])->name('order.tracking');
                Route::post('/{order}/return', [OrderController::class, 'returnOrderRequest'])->name('order.return');
            });
            Route::resource('orders', OrderController::class)->only(['index', 'show']);
        });

        Route::group(['prefix' => 'email'], function () {
            Route::get('/verify/{id}/{hash}', [EmailVerificationController::class, 'handler'])->middleware(['signed'])->name('verification.verify');
            Route::view('/verify', 'auth.verify-email')->name('verification.notice');
            Route::post('/verification-notification', [EmailVerificationController::class, 'resend'])->middleware(['throttle:6,1'])->name('verification.send');
        });

        Route::post('/logout', [UserController::class, 'logout'])->name('logout');
    });
});

resources/views/pages/blog_category_list.blade.php
@extends('layouts.master')
@section('title', 'Blog Post Category List')
@section('content')
    <div class="breadcrumb">
        <div class="container">
            <div class="breadcrumb-inner">
                <ul class="list-inline list-unstyled">
                    <li><a href="#">Home</a></li>
                    <li class='w-40'><a href="{{ route('blog.index') }}">All Blog Post</a></li>
                    <li class='active'>Blog Post Category</li>
                </ul>
            </div><!-- /.breadcrumb-inner -->
        </div><!-- /.container -->
    </div><!-- /.breadcrumb -->
    <div class="body-content">
        <div class="container">
            <div class="row">
                <div class="blog-page">
                    <div class="col-md-9">
                        <h1 class='text-5xl mb-5'>
                            Category: {{ $post_category->name }}
                        </h1>
                        @foreach ($posts as $blog)
                            <div class="blog-post  wow fadeInUp">
                                <a href="{{ route('blog.details', ['slug' => $blog->slug, 'id' => $blog->id]) }}"><img
                                        class="img-responsive" src="{{ asset($blog->image) }}" alt=""></a>
                                <h1><a href="{{ route('blog.details', ['slug' => $blog->slug, 'id' => $blog->id]) }}">{{ $blog->title }}
                                    </a></h1>
                                <span class="date-time">
                                    {{ $blog->created_at->diffForHumans() }}</span>
                                <p>{!! Str::limit($blog->details, 200) !!} </p>
                                <a href="{{ route('blog.details', ['slug' => $blog->slug, 'id' => $blog->id]) }}"
                                    class="btn btn-upper btn-primary read-more">read more</a>
                            </div>
                        @endforeach
                        <div class="clearfix blog-pagination filters-container  wow fadeInUp"
                            style="padding:0px; background:none; box-shadow:none; margin-top:15px; border:none">
                            <div class="text-right">
                                <div class="pagination-container">
                                    <ul class="list-inline list-unstyled">
                                        <li class="prev"><a href="#"><i class="fa fa-angle-left"></i></a></li>
                                        <li><a href="#">1</a></li>
                                        <li class="active"><a href="#">2</a></li>
                                        <li><a href="#">3</a></li>
                                        <li><a href="#">4</a></li>
                                        <li class="next"><a href="#"><i class="fa fa-angle-right"></i></a></li>
                                    </ul><!-- /.list-inline -->
                                </div><!-- /.pagination-container -->
                            </div><!-- /.text-right -->
                        </div><!-- /.filters-container -->
                    </div>
                    <div class="col-md-3 sidebar">
                        <div class="sidebar-module-container">
                            <div class="search-area outer-bottom-small">
                                <form>
                                    <div class="control-group">
                                        <input placeholder="Type to search" class="search-field">
                                        <a href="#" class="search-button"></a>
                                    </div>
                                </form>
                            </div>
                            <div class="home-banner outer-top-n outer-bottom-xs">
                                <img src="{{ asset('assets/images/banners/LHS-banner.jpg') }} " width='100%' alt="Image">
                            </div>
                            
                            <x-sidebar.blog.category :postCategories='$postCategories' />

                            <x-product-tags />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endsection

resources/views/pages/blog_details.blade.php
@extends('layouts.master')
@section('title', 'Blog Details')
@section('content')
    <div class="breadcrumb">
        <div class="container">
            <div class="breadcrumb-inner">
                <ul class="list-inline list-unstyled">
                    <li><a href="#">Home</a></li>
                    <li class='w-40'><a href="{{ route('blog.index') }}">All Blog Post</a></li>
                    <li class='active'>Blog Details</li>
                </ul>
            </div><!-- /.breadcrumb-inner -->
        </div><!-- /.container -->
    </div><!-- /.breadcrumb -->
    <div class="body-content">
        <div class="container">
            <div class="row">
                <div class="blog-page">
                    <div class="col-md-9">
                        <div class="blog-post wow fadeInUp">
                            <img class="img-responsive" src="{{ asset($post->image) }}" alt="">
                            <h1 class='my-4'>{{ $post->title }} </h1>
                            <span class="date-time">{{ $post->created_at->diffForHumans() }}</span>
                            <!-- Go to www.addthis.com/dashboard to customize your tools -->
                            <div class="addthis_inline_share_toolbox"></div>
                            <p> {!! $post->details !!} </p>
                            <!-- Go to www.addthis.com/dashboard to customize your tools -->
                            <div class="addthis_inline_share_toolbox"></div>
                        </div>
                        <div class="blog-write-comment outer-bottom-xs outer-top-xs">
                            <div class="row">
                                <div class="col-md-12">
                                    <h4>Leave A Comment</h4>
                                </div>
                                <div class="col-md-4">
                                    <form class="register-form" role="form">
                                        <div class="form-group">
                                            <label class="info-title" for="exampleInputName">Your Name
                                                <span>*</span></label>
                                            <input type="email" class="form-control unicase-form-control text-input"
                                                id="exampleInputName" placeholder="">
                                        </div>
                                    </form>
                                </div>
                                <div class="col-md-4">
                                    <form class="register-form" role="form">
                                        <div class="form-group">
                                            <label class="info-title" for="exampleInputEmail1">Email Address
                                                <span>*</span></label>
                                            <input type="email" class="form-control unicase-form-control text-input"
                                                id="exampleInputEmail1" placeholder="">
                                        </div>
                                    </form>
                                </div>
                                <div class="col-md-4">
                                    <form class="register-form" role="form">
                                        <div class="form-group">
                                            <label class="info-title" for="exampleInputTitle">Title
                                                <span>*</span></label>
                                            <input type="email" class="form-control unicase-form-control text-input"
                                                id="exampleInputTitle" placeholder="">
                                        </div>
                                    </form>
                                </div>
                                <div class="col-md-12">
                                    <form class="register-form" role="form">
                                        <div class="form-group">
                                            <label class="info-title" for="exampleInputComments">Your Comments
                                                <span>*</span></label>
                                            <textarea class="form-control unicase-form-control"
                                                id="exampleInputComments"></textarea>
                                        </div>
                                    </form>
                                </div>
                                <div class="col-md-12 outer-bottom-small m-t-20">
                                    <button type="submit" class="btn-upper btn btn-primary checkout-page-button">Submit
                                        Comment</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 sidebar">
                        <div class="sidebar-module-container">
                            <div class="search-area outer-bottom-small">
                                <form>
                                    <div class="control-group">
                                        <input placeholder="Type to search" class="search-field">
                                        <a href="#" class="search-button"></a>
                                    </div>
                                </form>
                            </div>
                            <div class="home-banner outer-top-n outer-bottom-xs">
                                <img src="{{ asset('assets/images/banners/LHS-banner.jpg') }}" width='100%' alt="Image">
                            </div>

                            <x-sidebar.blog.category :postCategories='$postCategories' />

                            <x-product-tags />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('scripts')
    <!-- Go to www.addthis.com/dashboard to customize your tools -->
    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-6140d5de19ff65b2"></script>
@endpush

resources/views/pages/blog_list.blade.php
@extends('layouts.master')
@section('title', 'Blog Page')
@section('content')
    <div class="breadcrumb">
        <div class="container">
            <div class="breadcrumb-inner">
                <ul class="list-inline list-unstyled">
                    <li><a href="#">Home</a></li>
                    <li class='active'>Blog</li>
                </ul>
            </div><!-- /.breadcrumb-inner -->
        </div><!-- /.container -->
    </div><!-- /.breadcrumb -->
    <div class="body-content">
        <div class="container">
            <div class="row">
                <div class="blog-page">
                    <div class="col-md-9">
                        @foreach ($posts as $blog)
                            <div class="blog-post  wow fadeInUp">
                                <a href="{{ route('blog.details', ['slug' => $blog->slug, 'id' => $blog->id]) }}">
                                    <img class="img-responsive" src="{{ asset($blog->image) }}" alt="{{ $blog->title }}"
                                        width='100%'>
                                </a>
                                <h1 class='my-4'><a
                                        href="{{ route('blog.details', ['slug' => $blog->slug, 'id' => $blog->id]) }}">
                                        {{ $blog->title }}</a></h1>
                                <span class="date-time">
                                    {{ $blog->created_at->diffForHumans() }}</span>
                                <p>{!! Str::limit($blog->details, 200) !!} </p>
                                <a href="{{ route('blog.details', ['slug' => $blog->slug, 'id' => $blog->id]) }}"
                                    class="btn btn-upper btn-primary read-more">read more</a>
                            </div>
                        @endforeach
                        <div class="clearfix blog-pagination filters-container  wow fadeInUp"
                            style="padding:0px; background:none; box-shadow:none; margin-top:15px; border:none">
                            <div class="text-right">
                                {{ $posts->links() }}
                            </div><!-- /.text-right -->
                        </div><!-- /.filters-container -->
                    </div>
                    <div class="col-md-3 sidebar">
                        <div class="sidebar-module-container">
                            <div class="search-area outer-bottom-small">
                                <form>
                                    <div class="control-group">
                                        <input placeholder="Type to search" class="search-field">
                                        <a href="#" class="search-button"></a>
                                    </div>
                                </form>
                            </div>
                            <div class="home-banner outer-top-n outer-bottom-xs">
                                <img src="{{ asset('assets/images/banners/LHS-banner.jpg') }} " width='100%' alt="Image">
                            </div>
                            <x-sidebar.blog.category :postCategories='$postCategories' />

                            <x-product-tags />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endsection